# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

stages:
  - test
  - build

services:
  - docker:dind

cache:
  paths:
    - .stack
    - .stack-work


before_script:
  - apt-get -y update
  - apt-get -y install libgmp-dev curl build-essential netbase libffi-dev ca-certificates
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - curl -sSL "https://get.haskellstack.org/" | sh
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY


test:
  stage: test
  script:
    - stack test
    

build-master:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

build:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master